let stations = [
  {
    code: "GWL",
    name: "GWALIOR",
    zone: "NCR",
    address: "Gwalior Junction Railway Station, Gwal...",
    state: "Madhya Pradesh",
  },
  {
    code: "DBA",
    name: "DABRA",
    zone: "NCR",
    address: "Dabra, Madhya Pradesh, India",
    state: "Madhya Pradesh",
  },
  {
    code: "DAA",
    name: "DATIA",
    zone: "NCR",
    address: "Datia Railway Station, Datia, Madhya P...",
    state: "Madhya Pradesh",
  },
  {
    code: "VGLB",
    name: "VIRANGANA LAKSHMIBAI",
    zone: "NCR",
    address: "Jhansi Junction Railway Station, Jhans...",
    state: "Uttar Pradesh",
  },
  {
    code: "NEW",
    name: "NIVARI",
    zone: "NCR",
    address: "Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MRPR",
    name: "MAU RANIPUR",
    zone: "NCR",
    address: "Jhansi, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "HPP",
    name: "HARPALPUR",
    zone: "NCR",
    address: "Harpalpur, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "BTX",
    name: "BELA TAL",
    zone: "NCR",
    address: "Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "KLAR",
    name: "KULPAHAR",
    zone: "NCR",
    address: "Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MBA",
    name: "MAHOBA",
    zone: "NCR",
    address: "Mahoba Railway Station, Mahoba, Uttar ...",
    state: "Uttar Pradesh",
  },
  {
    code: "BNDA",
    name: "BANDA JN",
    zone: "NCR",
    address: "Banda, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "ATE",
    name: "ATARRA",
    zone: "NCR",
    address: "Atarra Railway Station, Atarra, Uttar ...",
    state: "Uttar Pradesh",
  },
  {
    code: "CKTD",
    name: "CHITRAKOOTDHAM",
    zone: "NCR",
    address: "Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MKP",
    name: "MANIKPUR JN",
    zone: "NCR",
    address: "Manikpur, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "SRJ",
    name: "SHANKARGARH",
    zone: "NCR",
    address: "Chundwa, Uttar Pradesh 212108, India",
    state: "Uttar Pradesh",
  },
  {
    code: "NYN",
    name: "NAINI",
    zone: "NCR",
    address: "Naini, Allahabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "PRYJ",
    name: "PRAYAGRAJ JN",
    zone: "NCR",
    address: "Prayagraj Railway Station, Prayagraj, ...",
    state: "Uttar Pradesh",
  },
  {
    code: "PRG",
    name: "PRAYAG JN",
    zone: "NR",
    address: "Allahabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "PFM",
    name: "PHAPHAMAU JN",
    zone: "NR",
    address: "Phaphamau, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "PLP",
    name: "PHULPUR",
    zone: "NR",
    address: "Pura Achchai, Phulpur, Uttar Pradesh, ...",
    state: "Uttar Pradesh",
  },
  {
    code: "URPR",
    name: "UGRASENPUR",
    zone: "NR",
    address: "Allahabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "JNH",
    name: "JANGHAI JN",
    zone: "NR",
    address: "Janghai Jn, Janghai, Uttar Pradesh 212...",
    state: "Uttar Pradesh",
  },
  {
    code: "SAW",
    name: "SURIAWAN",
    zone: "NR",
    address: "Suriyawan, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "BOY",
    name: "BHADOHI",
    zone: "NR",
    address: "Bhadohi Railway Station, Bhadohi, Utta...",
    state: "Uttar Pradesh",
  },
  {
    code: "BSBS",
    name: "BANARAS",
    zone: "NER",
    address: "Banaras Raliway Station, Varanasi, Utt...",
    state: "Uttar Pradesh",
  },
  {
    code: "KYQ",
    name: "KAMAKHYA",
    zone: "NFR",
    address: "Kamakhya Railway Station, Maligaon, Gu...",
    state: "Assam",
  },
  {
    code: "RNY",
    name: "RANGIYA JN",
    zone: "NFR",
    address: "Rangia, Assam, India",
    state: "Assam",
  },
  {
    code: "BPRD",
    name: "BARPETA ROAD",
    zone: "NFR",
    address: "Barpeta Road, Assam, India",
    state: "Assam",
  },
  {
    code: "NBQ",
    name: "NEW BONGAIGAON",
    zone: "NFR",
    address: "Bongaigaon, Assam, India",
    state: "Assam",
  },
  {
    code: "KOJ",
    name: "KOKRAJHAR",
    zone: "NFR",
    address: "Kokrajhar, Assam, India",
    state: "Assam",
  },
  {
    code: "NOQ",
    name: "NEW ALIPURDAUR",
    zone: "NFR",
    address: "New Aipur-Duar Railway Station, Alipur...",
    state: "West Bengal",
  },
  {
    code: "NCB",
    name: "NEW COOCH BEHAR",
    zone: "NFR",
    address: "New Cooch Behar Railway Station, Cooch...",
    state: "West Bengal",
  },
  {
    code: "JPE",
    name: "JALPAIGURI ROAD",
    zone: "NFR",
    address: "JPE, Jalpaiguri, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "NJP",
    name: "NEW JALPAIGURI",
    zone: "NFR",
    address: "New Jalpaguri Railway Station, Siligur...",
    state: "West Bengal",
  },
  {
    code: "KNE",
    name: "KISHANGANJ",
    zone: "NFR",
    address: "Kishanganj, Bihar, India",
    state: "Bihar",
  },
  {
    code: "BOE",
    name: "BARSOI JN",
    zone: "NFR",
    address: "Barsoi Junction Railway Station, Raghu...",
    state: "Bihar",
  },
  {
    code: "KIR",
    name: "KATIHAR JN",
    zone: "NFR",
    address: "Katihar Railway Station, Katihar, Biha...",
    state: "Bihar",
  },
  {
    code: "NNA",
    name: "NAUGACHIA",
    zone: "ECR",
    address: "Bhagalpur, Bihar, India",
    state: "Bihar",
  },
  {
    code: "MNE",
    name: "MANSI JN",
    zone: "ECR",
    address: "Mansi, Bihar, India",
    state: "Bihar",
  },
  {
    code: "KGG",
    name: "KHAGARIA JN",
    zone: "ECR",
    address: "Khagariya Railway Station, Khagaria, B...",
    state: "Bihar",
  },
  {
    code: "BGS",
    name: "BEGU SARAI",
    zone: "ECR",
    address: "Station Rd, Begusarai, Bihar, India",
    state: "Bihar",
  },
  {
    code: "BJU",
    name: "BARAUNI JN",
    zone: "ECR",
    address: "Barauni Jn., NH 28, Barauni, Bihar, In...",
    state: "Bihar",
  },
  {
    code: "PPTA",
    name: "PATLIPUTRA",
    zone: "ECR",
    address: "Rukanpura, Patna, Bihar 800025, India",
    state: "Bihar",
  },
  {
    code: "DNR",
    name: "DANAPUR",
    zone: "ECR",
    address: "Danapur Railway Station, Danapur, Khag...",
    state: "Bihar",
  },
  {
    code: "ARA",
    name: "ARA",
    zone: "ECR",
    address: "Anaith, Arrah, Bihar, India",
    state: "Bihar",
  },
  {
    code: "BXR",
    name: "BUXAR",
    zone: "ECR",
    address: "Buxar Railway Station, Pandey Patti, B...",
    state: "Bihar",
  },
  {
    code: "DDU",
    name: "PT DEEN DAYAL UPADHYAY JN",
    zone: "ECR",
    address: "Mughal Sarai, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "FTP",
    name: "FATEHPUR",
    zone: "NCR",
    address: "Krishna Colony, Harihar Ganj, Fatehpur...",
    state: "Uttar Pradesh",
  },
  {
    code: "CNB",
    name: "KANPUR CENTRAL",
    zone: "NCR",
    address: "Kanpur Central, Jaipuria Road, Mirpur,...",
    state: "Uttar Pradesh",
  },
  {
    code: "ETW",
    name: "ETAWAH",
    zone: "NCR",
    address: "Etawah, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "TDL",
    name: "TUNDLA JN",
    zone: "NCR",
    address: "Tundla, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "ALJN",
    name: "ALIGARH JN",
    zone: "NCR",
    address: "Aligarh Junction, Aligarh, Uttar Prade...",
    state: "Uttar Pradesh",
  },
  {
    code: "GZB",
    name: "GHAZIABAD",
    zone: "NR",
    address: "Ghaziabad Railway Station, Arya Nagar,...",
    state: "Uttar Pradesh",
  },
  {
    code: "ANVT",
    name: "ANAND VIHAR TRM",
    zone: "NR",
    address: "Anand Vihar Railway Station, Anand Vih...",
    state: "Delhi",
  },
  {
    code: "AGTL",
    name: "AGARTALA",
    zone: "NFR",
    address: "National Highway 44, Badharghat, Agart...",
    state: "Tripura",
  },
  {
    code: "ABSA",
    name: "AMBASA",
    zone: "NFR",
    address: "National Highway 44, Ambassa, Tripura,...",
    state: "Tripura",
  },
  {
    code: "DMR",
    name: "DHARMANAGAR",
    zone: "NFR",
    address: "Dharmanagar, Tripura, India",
    state: "Tripura",
  },
  {
    code: "NKMG",
    name: "NEW KARIMGANJ",
    zone: "NFR",
    address: "New Market Rd, Karimganj, Assam 788710...",
    state: "Assam",
  },
  {
    code: "BPB",
    name: "BADARPUR JN",
    zone: "NFR",
    address: "Assam 788803, India",
    state: "Assam",
  },
  {
    code: "HJI",
    name: "HOJAI",
    zone: "NFR",
    address: "Hojai, Assam, India",
    state: "Assam",
  },
  {
    code: "GHY",
    name: "GUWAHATI",
    zone: "NFR",
    address: "Guwahati Railway Station, Paltan Bazaa...",
    state: "Assam",
  },
  {
    code: "SDAH",
    name: "SEALDAH",
    zone: "ER",
    address: "Kolkata Sealdah Railway Station, Belia...",
    state: "West Bengal",
  },
  {
    code: "DGR",
    name: "DURGAPUR",
    zone: "ER",
    address: "Durgapur, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "ASN",
    name: "ASANSOL JN",
    zone: "ER",
    address: "Asansol Junction Railway Station, Asan...",
    state: "West Bengal",
  },
  {
    code: "DHN",
    name: "DHANBAD JN",
    zone: "ECR",
    address: "Dhanbad, Jharkhand 826001, India",
    state: "Jharkhand",
  },
  {
    code: "GAYA",
    name: "GAYA JN",
    zone: "ECR",
    address: "Gaya Railway Station, Gaya, Bihar, India",
    state: "Bihar",
  },
  {
    code: "NDLS",
    name: "NEW DELHI",
    zone: "NR",
    address: "New Delhi, Connaught Place, New Delhi,...",
    state: "Delhi",
  },
  {
    code: "LHU",
    name: "LOHARU",
    zone: "NWR",
    address: "Loharu, Haryana, India",
    state: "Haryana",
  },
  {
    code: "SDLP",
    name: "SADULPUR JN",
    zone: "NWR",
    address: "Sadulpur, Rajasthan, India",
    state: "Rajasthan",
  },
  {
    code: "CUR",
    name: "CHURU",
    zone: "NWR",
    address: "National Highway 65, Churu, Rajasthan,...",
    state: "Rajasthan",
  },
  {
    code: "RTGH",
    name: "RATANGARH JN",
    zone: "NWR",
    address: "Ratangarh, Rajasthan 331022, India",
    state: "Rajasthan",
  },
  {
    code: "SDGH",
    name: "SRI DUNGARGARH",
    zone: "NWR",
    address: "Churu, Rajasthan, India",
    state: "Rajasthan",
  },
  {
    code: "BKN",
    name: "BIKANER JN",
    zone: "NWR",
    address: "Bikaner Junction, Station Road, Sadul ...",
    state: "Rajasthan",
  },
  {
    code: "MTJ",
    name: "MATHURA JN",
    zone: "NCR",
    address: "Mathura, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "AGC",
    name: "AGRA CANTT",
    zone: "NCR",
    address: "Agra Cantonment Railway station, Idgah...",
    state: "Uttar Pradesh",
  },
  {
    code: "BPL",
    name: "BHOPAL JN",
    zone: "WCR",
    address: "Bhopal, Madhya Pradesh, India",
    state: "Madhya Pradesh",
  },
  {
    code: "NGP",
    name: "NAGPUR",
    zone: "CR",
    address: "Nagpur Railway Station, Nagpur, Mahara...",
    state: "Maharashtra",
  },
  {
    code: "CD",
    name: "CHANDRAPUR",
    zone: "CR",
    address: "Chandrapur Railway Station, Ganj Ward,...",
    state: "Maharashtra",
  },
  {
    code: "BPQ",
    name: "BALHARSHAH",
    zone: "CR",
    address: "Balharshah Railway Station, Balharshah...",
    state: "Maharashtra",
  },
  {
    code: "SKZR",
    name: "SIRPUR KAGAZNGR",
    zone: "SCR",
    address: "Sirpur-Kaghaznagar Railway Station, Ka...",
    state: "Telangana",
  },
  {
    code: "BPA",
    name: "BELAMPALLI",
    zone: "SCR",
    address: "Bellampalli, Andhra Pradesh, India",
    state: "Andhra Pradesh",
  },
  {
    code: "MCI",
    name: "MANCHIRYAL",
    zone: "SCR",
    address: "Manchiryal Railway Station, Mancherial...",
    state: "Telangana",
  },
  {
    code: "RDM",
    name: "RAMGUNDAM",
    zone: "SCR",
    address: "Ramagundam Railway Station, Ramagundam...",
    state: "Telangana",
  },
  {
    code: "KZJ",
    name: "KAZIPET JN",
    zone: "SCR",
    address: "Kazipet, Andhra Pradesh, India",
    state: "Andhra Pradesh",
  },
  {
    code: "SC",
    name: "SECUNDERABAD JN",
    zone: "SCR",
    address: "Secunderabad, Regimental Bazaar, Secun...",
    state: "Telangana",
  },
  {
    code: "HYB",
    name: "HYDERABAD DECAN",
    zone: "SCR",
    address: "Nampally, Hyderabad, Andhra Pradesh, I...",
    state: "Andhra Pradesh",
  },
  {
    code: "NZM",
    name: "H NIZAMUDDIN",
    zone: "NR",
    address: "Hazrat Nizamuddin Railway Station, Har...",
    state: "Delhi",
  },
  {
    code: "KCG",
    name: "KACHEGUDA",
    zone: "SCR",
    address: "Kacheguda, Hyderabad, Andhra Pradesh, ...",
    state: "Andhra Pradesh",
  },
  {
    code: "KRNT",
    name: "KURNOOL TOWN",
    zone: "SCR",
    address: "Kurnool Town Railway Station, Kurnool,...",
    state: "Andhra Pradesh",
  },
  {
    code: "GTL",
    name: "GUNTAKAL JN",
    zone: "SCR",
    address: "Guntakal, Andhra Pradesh, India",
    state: "Andhra Pradesh",
  },
  {
    code: "BAY",
    name: "BELLARY JN",
    zone: "SWR",
    address: "Bellary, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "HPT",
    name: "HOSPET JN",
    zone: "SWR",
    address: "Hospet, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "KBL",
    name: "KOPPAL",
    zone: "SWR",
    address: "Koppal, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "GDG",
    name: "GADAG JN",
    zone: "SWR",
    address: "Gadag Junction, Gadag, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "UBL",
    name: "HUBBALLI JN",
    zone: "SWR",
    address: "Hubli Railway Station, Hubli, Karnatak...",
    state: "Karnataka",
  },
  {
    code: "HVR",
    name: "HAVERI",
    zone: "SWR",
    address: "Haveri, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "DVG",
    name: "DAVANGERE",
    zone: "SWR",
    address: "Davanagere, Karnataka, India",
    state: "Karnataka",
  },
  {
    code: "ASK",
    name: "ARSIKERE JN",
    zone: "SWR",
    address: "Arsikere Junction Railway Station, Ars...",
    state: "Karnataka",
  },
  {
    code: "TK",
    name: "TUMKUR",
    zone: "SWR",
    address: "Tumkur Railway Station, Tumkur, Karnat...",
    state: "Karnataka",
  },
  {
    code: "YPR",
    name: "YESVANTPUR JN",
    zone: "SWR",
    address: "Tumkur Main Rd, Yeshwanthpur Industria...",
    state: "Karnataka",
  },
  {
    code: "MZP",
    name: "MIRZAPUR",
    zone: "NCR",
    address: "Mirzapur Railway Station, Mirzapur, Ut...",
    state: "Uttar Pradesh",
  },
  {
    code: "DLN",
    name: "DILDARNAGAR JN",
    zone: "ECR",
    address: "DLN Rd, Dildar Nagar, Bihar, India",
    state: "Bihar",
  },
  {
    code: "PRNA",
    name: "PURNIA JN",
    zone: "NFR",
    address: "Purnia Railway Sation, Purnia, Bihar, ...",
    state: "Bihar",
  },
  {
    code: "ARQ",
    name: "ARARIYA COURT",
    zone: "NFR",
    address: "Araria, Bihar, India",
    state: "Bihar",
  },
  {
    code: "FBG",
    name: "FORBESGANJ",
    zone: "NFR",
    address: "Forbesganj, Bihar, India",
    state: "Bihar",
  },
  {
    code: "JBN",
    name: "JOGBANI",
    zone: "NFR",
    address: "Jogbani Railway Station, Koshi Rajmarg...",
    state: "Bihar",
  },
  {
    code: "DLI",
    name: "DELHI",
    zone: "NR",
    address: "Old Delhi Junction, Hamilton Road, New...",
    state: "Delhi",
  },
  {
    code: "DSA",
    name: "DELHI SHAHDARA",
    zone: "NR",
    address: "Jawala Nagar, Shahdara, New Delhi, Del...",
    state: "Delhi",
  },
  {
    code: "KRJ",
    name: "KHURJA JN",
    zone: "NCR",
    address: "Bulandshahr, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "FZD",
    name: "FIROZABAD",
    zone: "NCR",
    address: "Firozabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "PHD",
    name: "PHAPHUND",
    zone: "NCR",
    address: "Phaphund Pata Rd, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "JJK",
    name: "JHINJHAK",
    zone: "NCR",
    address: "Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "RURA",
    name: "RURA",
    zone: "NCR",
    address: "Rura - Jhinjhak Canal Road, Rura, Utta...",
    state: "Uttar Pradesh",
  },
  {
    code: "BRE",
    name: "BHARWARI",
    zone: "NCR",
    address: "Bharwari, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "BDL",
    name: "VINDHYACHAL",
    zone: "NCR",
    address: "Vindhyachal main Road, Uttar Pradesh, ...",
    state: "Uttar Pradesh",
  },
  {
    code: "PNBE",
    name: "PATNA JN",
    zone: "ECR",
    address: "Patna Junction Railway Station, Mithap...",
    state: "Bihar",
  },
  {
    code: "BKP",
    name: "BAKHTIYARPUR JN",
    zone: "ECR",
    address: "Bakhtiyarpur Junction, Bakhtiyarpur, B...",
    state: "Bihar",
  },
  {
    code: "MKA",
    name: "MOKAMEH JN",
    zone: "ECR",
    address: "Mokama, Mokameh Khas, Bihar 803302, In...",
    state: "Bihar",
  },
  {
    code: "NBJU",
    name: "NEW BARAUNI JN",
    zone: "ECR",
    address: "Barauni, Bihar 851210, India",
    state: "Bihar",
  },
  {
    code: "LKN",
    name: "LAKHMINIA",
    zone: "ECR",
    address: "Bihar, India",
    state: "Bihar",
  },
  {
    code: "SKJ",
    name: "SAHIBPUR KML JN",
    zone: "ECR",
    address: "National Highway 31, Bihar, India",
    state: "Bihar",
  },
  {
    code: "MSK",
    name: "MAHES KHUNT",
    zone: "ECR",
    address: "Maheshkhunt, Bihar, India",
    state: "Bihar",
  },
  {
    code: "PSR",
    name: "PASRAHA",
    zone: "ECR",
    address: "Khagaria, Bihar, India",
    state: "Bihar",
  },
  {
    code: "NNR",
    name: "NARAYANPUR",
    zone: "ECR",
    address: "Bhagalpur, Bihar, India",
    state: "Bihar",
  },
  {
    code: "THB",
    name: "THANA BIHPUR JN",
    zone: "ECR",
    address: "Bhagalpur, Bihar, India",
    state: "Bihar",
  },
  {
    code: "KUE",
    name: "KURSELA",
    zone: "ECR",
    address: "Simmar Gach Bus Stop, National Highway...",
    state: "Bihar",
  },
  {
    code: "CRR",
    name: "KARAGOLA ROAD",
    zone: "ECR",
    address: "Bihar, India",
    state: "Bihar",
  },
  {
    code: "SMO",
    name: "SEMAPUR",
    zone: "ECR",
    address: "Semapur Railway Station, Semapur, Biha...",
    state: "Bihar",
  },
  {
    code: "LAV",
    name: "LABHA",
    zone: "NFR",
    address: "Bihar, India",
    state: "Bihar",
  },
  {
    code: "AZR",
    name: "AZAMNAGAR ROAD",
    zone: "NFR",
    address: "Bihar, India",
    state: "Bihar",
  },
  {
    code: "DLK",
    name: "DALKOLHA",
    zone: "NFR",
    address: "Farsara, Bihar, India",
    state: "Bihar",
  },
  {
    code: "AUB",
    name: "ALUABARI ROAD",
    zone: "NFR",
    address: "Vivekananda Para, Narayanpur, Islampur...",
    state: "West Bengal",
  },
  {
    code: "TKG",
    name: "THAKURGANJ",
    zone: "NFR",
    address: "Thakurganj, Bihar, India",
    state: "Bihar",
  },
  {
    code: "BORA",
    name: "BAGHDOGRA",
    zone: "NFR",
    address: "Bagdogra Airport (IXB), Bagdogra, West...",
    state: "West Bengal",
  },
  {
    code: "SGUJ",
    name: "SILIGURI JN",
    zone: "NFR",
    address: "Siliguri Junction, Hill Cart Road, Sil...",
    state: "West Bengal",
  },
  {
    code: "NMZ",
    name: "NEW MAL JN",
    zone: "NFR",
    address: "Haihai Pathar Tea Garden I P, West Ben...",
    state: "West Bengal",
  },
  {
    code: "BNV",
    name: "BINNAGURI",
    zone: "NFR",
    address: "Binnaguri, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "DLO",
    name: "DALGAON",
    zone: "NFR",
    address: "Birpara, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "HSA",
    name: "HASIMARA",
    zone: "NFR",
    address: "Hasimara, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "APDJ",
    name: "ALIPUR DUAR JN",
    zone: "NFR",
    address: "Jalpaiguri, West Bengal, India",
    state: "West Bengal",
  },
  {
    code: "ASR",
    name: "AMRITSAR JN",
    zone: "NR",
    address: "Amritsar Junction Railway Station, Put...",
    state: "Punjab",
  },
  {
    code: "JNL",
    name: "JANDIALA",
    zone: "NR",
    address: "Jandiala Railway Station, Punjab, India",
    state: "Punjab",
  },
  {
    code: "BEAS",
    name: "BEAS",
    zone: "NR",
    address: "Beas, Punjab, India",
    state: "Punjab",
  },
  {
    code: "JUC",
    name: "JALANDHAR CITY",
    zone: "NR",
    address: "Jalandhar Railway Station, Jalandhar, ...",
    state: "Punjab",
  },
  {
    code: "JRC",
    name: "JALANDHAR CANT",
    zone: "NR",
    address: "Jalandhar, Punjab, India",
    state: "Punjab",
  },
  {
    code: "PGW",
    name: "PHAGWARA JN",
    zone: "NR",
    address: "Phagwara Railway Station, Phagwara, Pu...",
    state: "Punjab",
  },
  {
    code: "PHR",
    name: "PHILLAUR JN",
    zone: "NR",
    address: "Phillaur, Punjab, India",
    state: "Punjab",
  },
  {
    code: "LDH",
    name: "LUDHIANA JN",
    zone: "NR",
    address: "Ludhiana, Punjab, India",
    state: "Punjab",
  },
  {
    code: "SNL",
    name: "SANAHWAL",
    zone: "NR",
    address: "Ludhiana, Punjab 141016, India",
    state: "Punjab",
  },
  {
    code: "DOA",
    name: "DORAHA",
    zone: "NR",
    address: "Doraha, Punjab, India",
    state: "Punjab",
  },
  {
    code: "CHA",
    name: "CHAWAPALL",
    zone: "NR",
    address: "Punjab 141421, India",
    state: "Punjab",
  },
  {
    code: "KNN",
    name: "KHANNA",
    zone: "NR",
    address: "Khanna, Punjab, India",
    state: "Punjab",
  },
  {
    code: "GVG",
    name: "GOVINDGARH",
    zone: "NR",
    address: "Mandi Gobindgarh, Punjab, India",
    state: "Punjab",
  },
  {
    code: "SIR",
    name: "SIRHIND JN",
    zone: "NR",
    address: "Sirhind, Punjab, India",
    state: "Punjab",
  },
  {
    code: "RPJ",
    name: "RAJPURA JN",
    zone: "NR",
    address: "Rajpura, Punjab, India",
    state: "Punjab",
  },
  {
    code: "UBC",
    name: "AMBALA CITY",
    zone: "NR",
    address: "Ambala City, Haryana 134001, India",
    state: "Haryana",
  },
  {
    code: "UMB",
    name: "AMBALA CANT JN",
    zone: "NR",
    address: "134003, India",
    state: "Haryana",
  },
  {
    code: "RAA",
    name: "BARARA",
    zone: "NR",
    address: "Barara Railway Station, Barara, Haryan...",
    state: "Haryana",
  },
  {
    code: "JUDW",
    name: "JAGADHRI WSHOP",
    zone: "NR",
    address: "Yamunanagar, Haryana, India",
    state: "Haryana",
  },
  {
    code: "YJUD",
    name: "YAMUNANAGAR JAGADHRI",
    zone: "NR",
    address: "Yamunanagar, Haryana, India",
    state: "Haryana",
  },
  {
    code: "SRE",
    name: "SAHARANPUR",
    zone: "NR",
    address: "Saharanpur Railway Station, Subhash Na...",
    state: "Uttar Pradesh",
  },
  {
    code: "DBD",
    name: "DEOBAND",
    zone: "NR",
    address: "Deoband, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MOZ",
    name: "MUZAFFARNAGAR",
    zone: "NR",
    address: "Muzaffarnagar Railway Station, Civil L...",
    state: "Uttar Pradesh",
  },
  {
    code: "KAT",
    name: "KHATAULI",
    zone: "NR",
    address: "Shivpuri, Khatauli, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "DRLA",
    name: "DAURALA",
    zone: "NR",
    address: "Daurala, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MUT",
    name: "MEERUT CANT",
    zone: "NR",
    address: "Meerut, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "MTC",
    name: "MEERUT CITY",
    zone: "NR",
    address: "Meerut Railway Station, Meerut, Uttar ...",
    state: "Uttar Pradesh",
  },
  {
    code: "MDNR",
    name: "MODINAGAR",
    zone: "NR",
    address: "Modinagar, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "GUH",
    name: "GULDHAR",
    zone: "NR",
    address: "Ghaziabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "SBB",
    name: "SAHIBABAD",
    zone: "NR",
    address: "Sahibabad Industrial Area Site 4, Ghaz...",
    state: "Uttar Pradesh",
  },
  {
    code: "BVH",
    name: "BALLABGARH",
    zone: "NR",
    address: "Sector 25, Faridabad, Haryana, India",
    state: "Haryana",
  },
  {
    code: "PWL",
    name: "PALWAL",
    zone: "NR",
    address: "Palwal Railway Station, Palwal, Haryan...",
    state: "Haryana",
  },
  {
    code: "KSV",
    name: "KOSI KALAN",
    zone: "NCR",
    address: "Kosi Kalan, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "CHJ",
    name: "CHATA",
    zone: "NCR",
    address: "Mathura, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "RKM",
    name: "RAJA KI MANDI",
    zone: "NCR",
    address: "Pedestrian Overpass, Loha Mandi, Agra,...",
    state: "Uttar Pradesh",
  },
  {
    code: "DHO",
    name: "DHAULPUR",
    zone: "NCR",
    address: "Dhaulpur Railway Station, Dholpur, Raj...",
    state: "Rajasthan",
  },
  {
    code: "MRA",
    name: "MORENA",
    zone: "NCR",
    address: "Morena, Madhya Pradesh, India",
    state: "Madhya Pradesh",
  },
  {
    code: "TBT",
    name: "TALBAHAT",
    zone: "NCR",
    address: "Khandi, Uttar Pradesh 284126, India",
    state: "Uttar Pradesh",
  },
  {
    code: "LAR",
    name: "LALITPUR",
    zone: "NCR",
    address: "Lalitpur, Uttar Pradesh 284403, India",
    state: "Uttar Pradesh",
  },
  {
    code: "BINA",
    name: "BINA JN",
    zone: "WCR",
    address: "Bina, Madhya Pradesh, India",
    state: "Madhya Pradesh",
  },
  {
    code: "MABA",
    name: "MANDI BAMORA",
    zone: "WCR",
    address: "Mandi Bamora Station, Mandi Bamora, Ma...",
    state: "Madhya Pradesh",
  },
  {
    code: "BAQ",
    name: "GANJ BASODA",
    zone: "WCR",
    address: "Ganj Basoda Station, Ganj Basoda, Madh...",
    state: "Madhya Pradesh",
  },
  {
    code: "BHS",
    name: "VIDISHA",
    zone: "WCR",
    address: "Baripura , Vidisha, Madhya Pradesh, In...",
    state: "Madhya Pradesh",
  },
  {
    code: "RKMP",
    name: "RANI KAMLAPATI",
    zone: "WCR",
    address: "Habibganj Railway Station, Bhopal, Mad...",
    state: "Madhya Pradesh",
  },
  {
    code: "HBD",
    name: "HOSHANGABAD",
    zone: "WCR",
    address: "Hoshangabad Railway Station, Hoshangab...",
    state: "Madhya Pradesh",
  },
  {
    code: "ET",
    name: "ITARSI JN",
    zone: "WCR",
    address: "Itarsi Junction Railway Station, Itars...",
    state: "Madhya Pradesh",
  },
  {
    code: "GDYA",
    name: "GHORADONGRI",
    zone: "CR",
    address: "Ghoradongri Station, Ghoradongri, Madh...",
    state: "Madhya Pradesh",
  },
  {
    code: "BZU",
    name: "BETUL",
    zone: "CR",
    address: "Betul Railway Station, Betul, Madhya P...",
    state: "Madhya Pradesh",
  },
  {
    code: "AMLA",
    name: "AMLA JN",
    zone: "CR",
    address: "Amla Junction Railway Station, Amla, M...",
    state: "Madhya Pradesh",
  },
  {
    code: "MTY",
    name: "MULTAI",
    zone: "CR",
    address: "Multai Railway Station, Multai, Madhya...",
    state: "Madhya Pradesh",
  },
  {
    code: "KP",
    name: "KAMPTEE",
    zone: "SECR",
    address: "Kamptee Railway Station, Kamthi, Mahar...",
    state: "Maharashtra",
  },
  {
    code: "BRD",
    name: "BHANDARA ROAD",
    zone: "SECR",
    address: "Bhandara, Maharashtra, India",
    state: "Maharashtra",
  },
  {
    code: "TMR",
    name: "TUMSAR ROAD",
    zone: "SECR",
    address: "Bhandara, Maharashtra, India",
    state: "Maharashtra",
  },
  {
    code: "TRO",
    name: "TIRORA",
    zone: "SECR",
    address: "Tirora, Maharashtra, India",
    state: "Maharashtra",
  },
  {
    code: "G",
    name: "GONDIA JN",
    zone: "SECR",
    address: "Gondia Junction Railway Station, Rail ...",
    state: "Maharashtra",
  },
  {
    code: "AGN",
    name: "AMGAON",
    zone: "SECR",
    address: "Risama, Amgaon, Maharashtra, India",
    state: "Maharashtra",
  },
  {
    code: "SKS",
    name: "SALEKASA",
    zone: "SECR",
    address: "Salekasa, Maharashtra, India",
    state: "Maharashtra",
  },
  {
    code: "DGG",
    name: "DONGARGARH",
    zone: "SECR",
    address: "Dongargarh, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "RJN",
    name: "RAJ NANDGAON",
    zone: "SECR",
    address: "Rajnandgaon, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "DURG",
    name: "DURG",
    zone: "SECR",
    address: "Durg Railway Station, Durg, Chhattisga...",
    state: "Chhattisgarh",
  },
  {
    code: "BPHB",
    name: "BHILAI PWR HS",
    zone: "SECR",
    address: "Bhilai Power House Railway Station, Bh...",
    state: "Chhattisgarh",
  },
  {
    code: "R",
    name: "RAIPUR JN",
    zone: "SECR",
    address: "Raipur Junction Railway Station, Raipu...",
    state: "Chhattisgarh",
  },
  {
    code: "TLD",
    name: "TILDA",
    zone: "SECR",
    address: "Pathari - Boharhi, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "BYT",
    name: "BHATAPARA",
    zone: "SECR",
    address: "Bhatapara Railway Station, Bhatapara, ...",
    state: "Chhattisgarh",
  },
  {
    code: "BSP",
    name: "BILASPUR JN",
    zone: "SECR",
    address: "Bilaspur Junction Railway Station, Tar...",
    state: "Chhattisgarh",
  },
  {
    code: "FDB",
    name: "FARIDABAD",
    zone: "NR",
    address: "121003, India",
    state: "Haryana",
  },
  {
    code: "CHH",
    name: "CHAUKHANDI",
    zone: "NR",
    address: "Varanasi, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
  {
    code: "KRBA",
    name: "KORBA",
    zone: "SECR",
    address: "Korba Railway Station, Korba, Chhattis...",
    state: "Chhattisgarh",
  },
  {
    code: "URGA",
    name: "URGA",
    zone: "SECR",
    address: "Korba, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "SRBA",
    name: "SARAGBUNDIA",
    zone: "SECR",
    address: "Urga, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "MWRN",
    name: "MADWARANI",
    zone: "SECR",
    address: "Korba, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "KTHD",
    name: "KOTHARI ROAD",
    zone: "SECR",
    address: "Kothari Rd, Nungambakkam, Chennai, Tam...",
    state: "Chhattisgarh",
  },
  {
    code: "BPRH",
    name: "BALPUR HALT",
    zone: "SECR",
    address: "Ganga Reddy Nagar Colony Bus Stop, Mad...",
    state: "Chhattisgarh",
  },
  {
    code: "CPH",
    name: "CHAMPA",
    zone: "SECR",
    address: "Champa, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "NIA",
    name: "NAILA",
    zone: "SECR",
    address: "Station Road, Naila, Janjgir, Chhattis...",
    state: "Chhattisgarh",
  },
  {
    code: "AKT",
    name: "AKALTARA",
    zone: "SECR",
    address: "Akaltara, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "JRMG",
    name: "JAIRAMNAGAR",
    zone: "SECR",
    address: "Bilaspur, Chhattisgarh, India",
    state: "Chhattisgarh",
  },
  {
    code: "MUD",
    name: "MURADNAGAR",
    zone: "NR",
    address: "Ghaziabad, Uttar Pradesh, India",
    state: "Uttar Pradesh",
  },
];

exports.stations = stations;
